### ISSUE TITLE
Filters do not work well

### ISSUE THREAD

**Issue by rgovindji** [stoffern/gl-react-instagramfilters#1]
Hey awesome plugin! Some of these filters aren't working correctly. I get a washed out image or completely black. Also is there a reason you have hard coded urls to the github repo in the filter source files?

Here's what I see:
![screen shot 2016-08-14 at 5 05 29 pm](https://cloud.githubusercontent.com/assets/251495/17652061/6e7cc618-6241-11e6-9690-3baca866899a.png)

**Comment by st0ffern** [comment]
@rgovindji i know. I think thisone is related to `gl-react-native`
There is a long thread on it here: https://github.com/dcworldwide/react-native-gl-image-filter-examples/issues/1

**_update**_
The shaders is 100% correct.
I will try to add a manual preload to the images before `gl-react-native` loads to see if it helps.

**_update 2**_
Preloading does not seem to solve the problem.
Current working filters are:

```
Toaster
LordKelvin
F1977
Brannan
```

**Comment by stoffern** [comment]
Working ones
```
Toaster
LordKelvin

**Comment by rgovindji** [comment]
Yup those are the ones that work for me as well, is it possible to reproduce most filters with your other repo https://github.com/stoffern/gl-react-imagefilters ? I was thinking of switching to that instead.

**Comment by st0ffern** [comment]
@rgovindji I think there is a problem with the GLSL itself for many of the filters.
The ones that are working have 1px shaderMaps and the ones that dont work have 3px shaderMap height. There may be a difference between the engine that runs the original and running them throu `gl-react`.

Running them with gl-react-imagefilters will be like running a pure CSS over them. The result will not be the same, as the Instagram filters have overlays and more.

Altho. I guess that is a good idea. Then there will be no copyright over them and it will be more a look-a-like than a pure copy.

Will look into it tomorrow

@dcworldwide a little headsup. i think i found the problem^^

**Comment by iamyy** [comment]
@stoffern Hi, stoffern. Great RN plugin!  

Is there any idea to resolve this problem that @rgovindji mentioned for now? 

 I have the same problem,  and I tried to resolve it whole night, but no progress... 

By the way, the hacked Instagram filters code is old( 5 years age ), can it be the reason that cause this problem? 

Thank you.

**Comment by dcworldwide** [comment]
@stoffern I'll owe you a beer or two if you have :)

**Comment by iamyy** [comment]
I think I just solved this problem. I changed some GLSL code of the filters. I'll submit a pull request later :)

**Comment by dcworldwide** [comment]
Nicely done.

**Comment by st0ffern** [comment]
@iamyy could you create a PR or specify what you changed so we can look into it? :wink:

**Comment by st0ffern** [comment]
just found the solution to it, Seems like the GL-React uv`s are all inverted, and on the original GLSL they are not.

**Comment by st0ffern** [comment]
Just updated the repo, it is working now :smiley:

@dcworldwide: you owe me a couple of beers :laughing:  
cc @rgovindji

**Comment by rgovindji** [comment]
ohh wow! Thanks for fixing this @stoffern  !!!

**Comment by st0ffern** [comment]
np :wink:

**Comment by iamyy** [comment]
Great!

**Comment by reza7rm** [comment]
I have a strange issue the filter only works when the same Image is loaded out of surface tag ,else it shows a kinda black(more like maroon) screen.
```                  
<Image key="imgmain" source={{ uri: this.state.theimage }} 
                            style={{ width: this.state.screenWidth, height: this.state.screenWidth }} resizeMode="contain" /> 

                        <Surface preload={true} height={this.state.screenWidth} width={this.state.screenWidth}>
                            <Amaro>
                                <Image key="imgAmaro" 
                                    source={{uri:this.state.theimage}}
                                    imageSize={{ width: this.state.screenWidth, height: this.state.screenWidth }}
                                    resizeMode="contain"
                                />
                            </Amaro>
                        </Surface>
```

by this code I have two images; one without filter and the other with filter applied, but as soon as I remove the first image the second image(filtered one) is gone and turns into a black one!
