### ISSUE TITLE
video

### ISSUE THREAD

**Issue by rf1804** [stoffern/gl-react-instagramfilters#14]
Is this package works with video also??

**Comment by st0ffern** [comment]
Yes it should, gl-react shaders should work with both images and video

**Comment by rf1804** [comment]
any example of video??

**Comment by st0ffern** [comment]
read gl-react docs or stackoverflow!

Issues are ment for problems and bugs, not documentation or questions

**Comment by rf1804** [comment]
thanks @stoffern i just did for help, 1 more thing o want to know is this package works on ios and android both?
