### ISSUE TITLE
installing the package

### ISSUE THREAD

**Issue by mopilo** [stoffern/gl-react-instagramfilters#16]
i tried installing this package but i keep getting could not find package.

**Comment by st0ffern** [comment]
If i say "my car wont start, whats wrong?" what do you answer?

**Comment by mopilo** [comment]
Am sorry i wasn't specific,  this my issue. after install the dependency and doing necessary settings, i got this error. " Configuration with name 'default' not found. "

i guess its explainatory.

**Comment by st0ffern** [comment]
one dependency to react-native link is not correctly installed read docs for every native plugin
