### ISSUE TITLE
Consuming too much memory

### ISSUE THREAD

**Issue by rgovindji** [stoffern/gl-react-instagramfilters#3]
Not really an issue but sometimes my app will crash when I try to load previews for each filter. I've tried shouldRasterizeIOS={true} on the views but that doesn't help. Do you have any suggestions on how to reduce the memory footprint, I'm seeing up to 1.2 GB of memory consumed.

**Comment by st0ffern** [comment]
well how big are your image files?
I know that if you have a 2 mb file and repeat a surface over that for all the thumbs it will consume alot.

The solution will then be to resize the thumbs as you dont need them that big..
If you continue to have this problem i suggest posting a memory dump and code to `gl-react-native` as this is just a shader set.

I have tested it with thumbs and it worked flawless after resizing and using normal sized images

**Comment by rgovindji** [comment]
Ahhhh great idea, going to try that! Thanks @stoffern

**Comment by superandrew213** [comment]
@rgovindji did you find an efficient way to show the filter previews. I resized mine to 50x50 but it still takes some time before they are all loaded.

**Comment by rgovindji** [comment]
@superandrew213 how bad is you performance? I'm using 'react-native-image-resizer' and resizing it to 60x60 but it does take a little bit of time to load all filter. It's not as bad as it was before though so I'm happy with the results.

**Comment by superandrew213** [comment]
@rgovindji about 5 seconds and sometimes some don't load for even longer. How long are yours taking?

**Comment by st0ffern** [comment]
You guys need to wrap your head around how to solve this in a normal way :laughing: 
- first of all, the thumbs should be spinners when loading.
- when loading. create a hidden surface with filter..
- captureFrame of the surface to generate a temp image.
- remove spinner and show image.
- clean surface from memory

while main image is a big surface..

**Comment by rgovindji** [comment]
@stoffern Alright that's a great idea!!! Cool I'll give it a shot and see what the improvements are. Memory hasn't been much of a concern but out of curiosity is there a method I can call on the surface to clear it from memory?

**Comment by st0ffern** [comment]
@rgovindji i allready have a component here that does all of the bullets in the list..
i could publish the code later on..

altho this should be somehow easy for js people to code :smile:

**Comment by rgovindji** [comment]
@stoffern I would really appreciate it! I was just starting to create my own :)

**Comment by superandrew213** [comment]
thanks @stoffern. I just started using gl-react and am still trying to get my head around it

**Comment by serhiipalash** [comment]
> first of all, the thumbs should be spinners when loading.
when loading. create a hidden surface with filter..
captureFrame of the surface to generate a temp image.
remove spinner and show image.
clean surface from memory

> i allready have a component here that does all of the bullets in the list..
i could publish the code later on..

Hi @stoffern ! Did you publish it? I will be very grateful to you for it. This will save me one day of work.

**Comment by st0ffern** [comment]
@serhiipalash did not publish it but i can do it tomorrow 😉

**Comment by serhiipalash** [comment]
>  did not publish it but i can do it tomorrow

Thanks @stoffern ! I almost did everything myself.
Can you give me advice on how I can determine when `<Surface> ... </ Surface>` is fully displayed with nested components? 
`onLoad` method fires much early.

**Comment by st0ffern** [comment]
@serhiipalash That is a gl-react question.
