### ISSUE TITLE
I am getting an Error when i test the example code

### ISSUE THREAD

**Issue by SvetoslavSlavov** [stoffern/gl-react-instagramfilters#6]
![simulator screen shot - iphone 8 plus - 2017-10-03 at 13 32 29](https://user-images.githubusercontent.com/16868443/31121076-78ba65fa-a83f-11e7-8b5a-eb5d386830f8.png) This is the error i get. The code i write is from the example 
```
<Surface height={1024} width={693}>
  <Hudson>
    <GLImage
      source="http://i.imgur.com/tCatS2c.jpg"
      imageSize={{ width: 1024, height: 693 }}
      resizeMode="cover"
    />
  </Hudson>
</Surface>
```

**Comment by st0ffern** [comment]
gl-react version 3 ?
